name: finalka
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  http: ^0.13.6
  flutter:
    sdk: flutter
  uuid: ^3.0.0
  intl: ^0.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/categories/
    - assets/restaurants/
    - assets/profile_pics/
    - assets/food/
    - assets/gyms/