name: finalka
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  http: ^0.13.6
  google_maps_flutter: ^2.2.3
  geolocator: ^14.0.0
  geocoding: ^2.1.1
  flutter:
    sdk: flutter
  uuid: 4.5.1
  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^4.8.2
  flutter_facebook_auth: 6.0.4
  sqflite: ^2.3.0
  path: ^1.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
dependency_overrides:
  geolocator_android: ^5.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/categories/
    - assets/profile_pics/
    - assets/food/
    - assets/gyms/
    - assets/logo/
    - assets/animations/