// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCY8FnMflfziXCEO1uxAvS0MtbsrOsR00',
    appId: '1:591405282741:web:53fe141f54d776c384d5fc',
    messagingSenderId: '591405282741',
    projectId: 'finalka-d5280',
    authDomain: 'finalka-d5280.firebaseapp.com',
    storageBucket: 'finalka-d5280.firebasestorage.app',
    measurementId: 'G-LMWV1Y57CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArkTz5J7MGxtVTnLw9xGFaih5r4Gwt04E',
    appId: '1:591405282741:android:714d36c95572b18584d5fc',
    messagingSenderId: '591405282741',
    projectId: 'finalka-d5280',
    storageBucket: 'finalka-d5280.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtjAL-2Og1TPnPM2SgfRIdpk2rrdzHgKI',
    appId: '1:591405282741:ios:805ac596729dfa4784d5fc',
    messagingSenderId: '591405282741',
    projectId: 'finalka-d5280',
    storageBucket: 'finalka-d5280.firebasestorage.app',
    androidClientId: '591405282741-6l4jfg1jefntr9d4deca354v4pccc9vb.apps.googleusercontent.com',
    iosClientId: '591405282741-uqnnscj6u9ogs17asfflqduevp3rtvga.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtjAL-2Og1TPnPM2SgfRIdpk2rrdzHgKI',
    appId: '1:591405282741:ios:805ac596729dfa4784d5fc',
    messagingSenderId: '591405282741',
    projectId: 'finalka-d5280',
    storageBucket: 'finalka-d5280.firebasestorage.app',
    androidClientId: '591405282741-6l4jfg1jefntr9d4deca354v4pccc9vb.apps.googleusercontent.com',
    iosClientId: '591405282741-uqnnscj6u9ogs17asfflqduevp3rtvga.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCY8FnMflfziXCEO1uxAvS0MtbsrOsR00',
    appId: '1:591405282741:web:35d62a4d63827b0d84d5fc',
    messagingSenderId: '591405282741',
    projectId: 'finalka-d5280',
    authDomain: 'finalka-d5280.firebaseapp.com',
    storageBucket: 'finalka-d5280.firebasestorage.app',
    measurementId: 'G-VPE9F8CPPP',
  );
}
